-- ============================================
-- Expanded Conversation Templates (20 per vertical)
-- ============================================

-- First, clear existing templates
DELETE FROM conversation_templates;

-- E-commerce Templates (20)
INSERT INTO conversation_templates (vertical, subject, message_content) VALUES
('E-commerce', 'Question about my order #12345', 'Hi, I placed an order last week but haven''t received any tracking information yet. Can you help me find out where my package is? My order number is #12345. Thank you!'),
('E-commerce', 'Need to return an item', 'I received my order yesterday but unfortunately the size doesn''t fit. How can I initiate a return? Do I need to print a label or will one be sent to me?'),
('E-commerce', 'Discount code not working', 'I''m trying to use the discount code SAVE20 but it keeps saying it''s invalid. The email said it''s valid until the end of the month. Can you help me apply it to my cart?'),
('E-commerce', 'Product arrived damaged', 'My order arrived today but the item is damaged. The box was dented and the product inside is broken. What''s the process for getting a replacement?'),
('E-commerce', 'Wrong item received', 'I ordered a blue sweater in size M but received a red one in size L. Can you help me exchange this for the correct item? Order #78901'),
('E-commerce', 'Shipping delay concerns', 'My order was supposed to arrive 3 days ago according to the estimated delivery date, but it still hasn''t shipped. Is there a problem with my order?'),
('E-commerce', 'Payment not processed', 'I tried to complete my purchase but got an error message. My card was charged but I didn''t receive an order confirmation. Can you check if my order went through?'),
('E-commerce', 'Question about product availability', 'I see the item I want is out of stock. Do you know when it will be restocked? I''d like to purchase it as soon as it''s available again.'),
('E-commerce', 'Cancellation request', 'I need to cancel order #56789 that I placed this morning. I accidentally ordered the wrong quantity. Is it too late to cancel?'),
('E-commerce', 'Membership benefits inquiry', 'I just signed up for your premium membership but I''m not seeing the free shipping option at checkout. How do I access my member benefits?'),
('E-commerce', 'Gift card balance check', 'I have a gift card but I''m not sure how much is left on it. Can you help me check the balance? The card number is GC-12345-ABCDE.'),
('E-commerce', 'Product recommendation needed', 'I''m looking for a laptop for graphic design work. Budget is around $1500. What would you recommend from your current inventory?'),
('E-commerce', 'Bulk order inquiry', 'I''m interested in ordering 50 units of product SKU-7890 for my company. Do you offer bulk pricing discounts? Can you provide a quote?'),
('E-commerce', 'International shipping question', 'Do you ship to Canada? I''m trying to place an order but I don''t see my country in the shipping options. Also, will I have to pay customs fees?'),
('E-commerce', 'Price match request', 'I found the same product on another website for $20 less. Do you have a price match policy? I''d prefer to buy from you if possible.'),
('E-commerce', 'Subscription management', 'I have a monthly subscription for your coffee delivery but I need to skip next month because I''ll be traveling. How can I pause my subscription temporarily?'),
('E-commerce', 'Product specifications inquiry', 'I''m interested in the wireless headphones but I need to know if they''re compatible with my Samsung phone. Also, what''s the battery life?'),
('E-commerce', 'Loyalty points question', 'I noticed my loyalty points weren''t added to my account after my last purchase. Can you check on this? My account email is customer@example.com'),
('E-commerce', 'Pre-order availability', 'I see that new product is available for pre-order. When will it actually ship? And will my card be charged now or when it ships?'),
('E-commerce', 'Order modification request', 'I just placed order #45678 but I forgot to add another item. Can I add it to my existing order before it ships, or do I need to place a separate order?'),

-- SaaS Templates (20)
INSERT INTO conversation_templates (vertical, subject, message_content) VALUES
('SaaS', 'Cannot log into my account', 'I''ve been trying to log into my account for the past hour but keep getting an error message saying "Invalid credentials" even though I''m sure my password is correct. Can you help me reset my password or check what''s wrong?'),
('SaaS', 'Upgrade subscription plan', 'I''m currently on the Basic plan but I need to upgrade to Pro to access the advanced features. What''s the pricing difference and will I be charged immediately or at the end of my billing cycle?'),
('SaaS', 'Feature request', 'I love your product but I really wish there was a dark mode option. Are there any plans to add this feature? It would make working late at night much easier on the eyes.'),
('SaaS', 'Integration not working', 'I''m trying to connect your app with my Slack workspace but it keeps failing at the authorization step. I''ve tried reconnecting multiple times. Can you help troubleshoot this?'),
('SaaS', 'Data export request', 'I need to export all my data from the platform for a quarterly report. What''s the best way to do this? I need it in CSV format if possible.'),
('SaaS', 'Billing discrepancy', 'I was charged $99 this month but my plan should be $79. Can you help me understand why there''s a difference? I haven''t made any changes to my account.'),
('SaaS', 'Team member access issue', 'I invited a new team member but they say they haven''t received the invitation email. Can you resend it or check if there''s an issue? Their email is teammate@company.com'),
('SaaS', 'API rate limit exceeded', 'My API integration stopped working and I''m getting a "rate limit exceeded" error. I''m on the Pro plan which should have higher limits. Can you check my account?'),
('SaaS', 'Account deletion request', 'I need to close my account and delete all my data. What''s the process for this? Will I receive a refund for the remaining days in my billing cycle?'),
('SaaS', 'Two-factor authentication problem', 'I enabled 2FA on my account but I lost my phone. Now I can''t log in. Can you help me disable 2FA so I can access my account again?'),
('SaaS', 'Performance issues', 'The app has been really slow for the past few days. Pages take forever to load and sometimes timeout. Is there an outage or maintenance happening?'),
('SaaS', 'Mobile app not syncing', 'Changes I make on the mobile app aren''t showing up on the web version. Is there a sync issue? I''ve tried logging out and back in but it didn''t help.'),
('SaaS', 'Custom domain setup', 'I''m trying to set up a custom domain for my workspace but I''m not sure how to configure the DNS settings. Can you provide step-by-step instructions?'),
('SaaS', 'SSO configuration help', 'We need to set up single sign-on for our organization using our Azure AD. Do you have documentation for this? Our IT team needs to know what information to configure.'),
('SaaS', 'Data retention policy question', 'How long do you keep deleted items before they''re permanently removed? I accidentally deleted an important file and need to recover it.'),
('SaaS', 'Webhook notification not received', 'I have webhooks configured but I''m not receiving notifications for new events. I checked the endpoint and it''s working fine. Can you help debug this?'),
('SaaS', 'Bulk user import', 'I need to add 200 users to our workspace. Is there a way to bulk import them from a CSV file instead of adding them one by one?'),
('SaaS', 'Trial extension request', 'My trial is ending in 2 days but I haven''t had time to fully evaluate all features. Is it possible to extend the trial for another week?'),
('SaaS', 'Permission settings confusion', 'I''m trying to restrict certain team members from accessing specific projects but I can''t figure out the permission settings. Can you explain how role-based access works?'),
('SaaS', 'Annual subscription discount', 'I''m currently on monthly billing but I''d like to switch to annual. Do you offer a discount for annual subscriptions? What''s the process to change?'),

-- Financial Services Templates (20)
INSERT INTO conversation_templates (vertical, subject, message_content) VALUES
('Financial Services', 'Question about recent transaction', 'I see a transaction on my account for $127.50 that I don''t recognize. It was processed on January 15th. Can you provide more details about this charge and help me understand what it''s for?'),
('Financial Services', 'Credit card not working', 'I tried to use my card at a store today but it was declined. I checked and I have sufficient funds. Can you tell me why my card isn''t working?'),
('Financial Services', 'Fraud alert on account', 'I received a text about suspicious activity on my account. I didn''t make those transactions. What should I do? Should I cancel my card?'),
('Financial Services', 'Interest rate inquiry', 'I''ve been a customer for 5 years and I''m wondering if I can get a better interest rate on my savings account. What rates are currently available?'),
('Financial Services', 'Statement not received', 'I haven''t received my monthly statement for December. Can you resend it to my email? I need it for my tax preparation.'),
('Financial Services', 'Direct deposit setup', 'I need to set up direct deposit with my new employer. What''s the routing number and account number they need? Can you provide that information?'),
('Financial Services', 'Overdraft fee dispute', 'I was charged an overdraft fee but I had money in my savings account. I thought I had overdraft protection set up. Can you waive this fee?'),
('Financial Services', 'Lost debit card', 'I lost my debit card and need to report it immediately. Can you freeze my account and send me a replacement card? How long will it take to arrive?'),
('Financial Services', 'Investment portfolio review', 'I''d like to review my investment portfolio and discuss rebalancing options. Can I schedule a call with a financial advisor this week?'),
('Financial Services', 'Loan application status', 'I submitted a mortgage application two weeks ago and haven''t heard back. Can you check the status? My application number is ML-789456.'),
('Financial Services', 'Online banking locked', 'My online banking account is locked after I entered my password wrong too many times. How can I unlock it? I need to make an urgent payment.'),
('Financial Services', 'Wire transfer question', 'I need to send an international wire transfer to the UK. What are the fees and how long will it take? Also, what information do I need from the recipient?'),
('Financial Services', 'Credit limit increase request', 'I''ve been using my credit card responsibly for over a year. Can I request a credit limit increase? My current limit is $5,000.'),
('Financial Services', 'Auto loan payment change', 'I need to change my auto loan payment due date from the 5th to the 20th of each month. Is this possible? My loan number is AL-456789.'),
('Financial Services', 'Account closure request', 'I''m moving abroad and need to close my checking account. What''s the process? Do I need to come to a branch or can I do it online?'),
('Financial Services', 'Checkbook reorder', 'I''m running low on checks and need to order more. How do I do this? How much do they cost and how long will delivery take?'),
('Financial Services', 'Beneficiary update', 'I need to update the beneficiary information on my retirement account. What documents do I need to provide? Can this be done online?'),
('Financial Services', 'Foreign transaction fees', 'I''m traveling to Europe next month. Will I be charged foreign transaction fees? Should I notify you before I travel to avoid my card being blocked?'),
('Financial Services', 'Mobile app not showing balance', 'The mobile app isn''t showing my current balance. It''s been stuck on the same amount for two days. Is there a technical issue?'),
('Financial Services', 'Recurring payment cancellation', 'I need to stop a recurring payment to a gym membership that I cancelled. The authorization number is REC-123456. Can you block future charges?'),

-- Healthcare Templates (20)
INSERT INTO conversation_templates (vertical, subject, message_content) VALUES
('Healthcare', 'Appointment rescheduling request', 'I need to reschedule my appointment scheduled for next Tuesday at 2pm due to an unexpected work conflict. Are there any available slots earlier in the week or later in the afternoon? Thank you for your help.'),
('Healthcare', 'Prescription refill needed', 'I need a refill for my blood pressure medication. I''ve been taking it for 6 months and I''m running low. Can my doctor approve a refill without an appointment?'),
('Healthcare', 'Test results inquiry', 'I had blood work done last week and was told results would be available in 3-5 days. It''s been a week and I haven''t heard anything. Can you check if my results are ready?'),
('Healthcare', 'Insurance coverage question', 'I''m not sure if my insurance covers the procedure my doctor recommended. Can you verify my coverage? My policy number is HC-789456123.'),
('Healthcare', 'Medical records request', 'I need copies of my medical records from the past year for a second opinion consultation. What''s the process to request these? Is there a fee?'),
('Healthcare', 'Billing statement clarification', 'I received a bill for $450 but I thought my insurance would cover most of this. Can you explain the charges and check if my insurance was properly billed?'),
('Healthcare', 'Urgent appointment needed', 'I''ve been experiencing severe headaches for three days and need to see a doctor as soon as possible. Do you have any urgent care slots available today or tomorrow?'),
('Healthcare', 'Referral to specialist', 'My primary care doctor said I need to see a cardiologist but I haven''t received the referral yet. Can you help me get this processed so I can make an appointment?'),
('Healthcare', 'Vaccination record', 'I need proof of my COVID-19 vaccination for travel purposes. Can you provide an official vaccination record? I need it by the end of this week.'),
('Healthcare', 'Telehealth appointment setup', 'I''d like to schedule a virtual appointment instead of coming to the office. Do you offer telehealth visits? How does that work?'),
('Healthcare', 'Medication side effects', 'I started a new medication three days ago and I''m experiencing some side effects. Should I be concerned? Can I speak to a nurse about this?'),
('Healthcare', 'Lab work fasting requirements', 'I have lab work scheduled for tomorrow morning. Do I need to fast beforehand? If so, for how many hours? Can I drink water?'),
('Healthcare', 'After-hours emergency guidance', 'My child has a fever of 103°F and I''m not sure if I should go to the ER or wait until morning. Can you provide guidance?'),
('Healthcare', 'Physical therapy referral', 'I''ve been having chronic back pain and my doctor mentioned physical therapy. How do I get a referral? Does my insurance require pre-authorization?'),
('Healthcare', 'Appointment confirmation', 'I think I have an appointment next week but I''m not sure of the date and time. Can you confirm when my next appointment is scheduled? My date of birth is 01/15/1985.'),
('Healthcare', 'New patient registration', 'I''m new to the area and need to establish care with a primary care physician. What information do I need to provide? Can I register online?'),
('Healthcare', 'Imaging results follow-up', 'I had an MRI done last Monday and my doctor''s office said they''d call with results in a few days. It''s been a week. Can you check on the status?'),
('Healthcare', 'Pre-surgery instructions', 'I have surgery scheduled for next week and I need to confirm the pre-operative instructions. What time should I arrive and what preparation is needed?'),
('Healthcare', 'Specialist recommendation', 'My doctor said I should see an orthopedist for my knee pain but didn''t give me a specific recommendation. Can you suggest someone in your network?'),
('Healthcare', 'Payment plan request', 'I received a large medical bill that I can''t pay all at once. Do you offer payment plans? What would the monthly payment options be?'),

-- Travel Templates (20)
INSERT INTO conversation_templates (vertical, subject, message_content) VALUES
('Travel', 'Flight cancellation and refund', 'My flight (booking reference: ABC123) was cancelled and I need to rebook for the same destination. What are my options and will I get a full refund for the cancelled flight? I need to travel within the next week.'),
('Travel', 'Upgrade to business class', 'I have a long-haul flight next month and I''d like to upgrade from economy to business class. What would be the cost difference? Do you have availability on flight TK456 on March 15th?'),
('Travel', 'Baggage allowance question', 'I''m flying internationally and I''m not sure about the baggage allowance. How many bags can I check and what are the weight limits? Will I be charged for extra bags?'),
('Travel', 'Hotel booking modification', 'I need to change my hotel reservation from March 10-12 to March 11-13. Is there a fee for changing dates? The confirmation number is HTL-789456.'),
('Travel', 'Visa requirements inquiry', 'I''m traveling to Brazil next month and I''m not sure if I need a visa. Can you provide information about visa requirements for US citizens?'),
('Travel', 'Loyalty points redemption', 'I have 50,000 loyalty points and I''d like to use them to book a flight to Hawaii. How do I redeem points? Can I pay with a combination of points and cash?'),
('Travel', 'Seat selection issue', 'I''m trying to select seats for my family of four but the system won''t let us sit together. Can you help us get adjacent seats? We have young children.'),
('Travel', 'Travel insurance claim', 'I had to cancel my trip due to a medical emergency and I purchased travel insurance. What''s the process to file a claim? What documents do I need?'),
('Travel', 'Airport lounge access', 'I have a long layover in Frankfurt. Do I have access to the airport lounge with my ticket class? If not, can I purchase a day pass?'),
('Travel', 'Group booking discount', 'I''m organizing a trip for 12 people to Barcelona. Do you offer group discounts? Can we get a group rate if we all book together?'),
('Travel', 'Special meal request', 'I have a vegetarian diet and I want to make sure a meal is available on my international flight. How do I request a special meal? My flight is on FL-456789.'),
('Travel', 'Connecting flight missed', 'I missed my connecting flight because my first flight was delayed. What are my options? Will you rebook me on the next available flight at no charge?'),
('Travel', 'Name correction on ticket', 'I made a typo when booking my ticket. My name is spelled incorrectly. How can I fix this? Is there a fee? My booking reference is BC-123456.'),
('Travel', 'Pet travel policy', 'I need to travel with my small dog. What''s your pet policy? Can small dogs travel in the cabin? What are the requirements and fees?'),
('Travel', 'Unaccompanied minor service', 'My 10-year-old daughter needs to fly alone to visit her grandparents. Do you offer an unaccompanied minor service? What''s the process and cost?'),
('Travel', 'Rental car inquiry', 'I''ve booked a flight and need to rent a car at my destination. Do you offer car rental through your booking system? Are there package discounts?'),
('Travel', 'Flight delay compensation', 'My flight was delayed by 6 hours causing me to miss an important meeting. Am I entitled to any compensation? Flight number was DL-789.'),
('Travel', 'Travel itinerary change', 'I need to add a stop in London to my existing booking from New York to Paris. Is it possible to modify my itinerary? What would the additional cost be?'),
('Travel', 'Wheelchair assistance request', 'My elderly mother needs wheelchair assistance at the airport. How do I arrange this? Should I request it when booking or closer to the travel date?'),
('Travel', 'Vacation package inquiry', 'I''m interested in a vacation package to Cancun including flight and hotel. Do you have any all-inclusive deals available for early May? I''m traveling with my spouse.'),

-- Telecom Templates (20)
INSERT INTO conversation_templates (vertical, subject, message_content) VALUES
('Telecom', 'Internet connection issues', 'My internet has been very slow for the past three days and keeps disconnecting every few hours. I''ve tried restarting the router multiple times but it hasn''t helped. Can you check if there''s an issue with my connection?'),
('Telecom', 'Upgrade mobile plan', 'I keep running out of data each month. I''m currently on the 5GB plan but I need more. What are my upgrade options and how much would it cost to move to the unlimited plan?'),
('Telecom', 'Bill higher than usual', 'My bill this month is $45 higher than normal. I haven''t made any changes to my service. Can you help me understand why there''s this increase?'),
('Telecom', 'Service outage reported', 'My internet and TV have been down since this morning. Is there an outage in my area? If so, when will service be restored? My account number is TC-789456.'),
('Telecom', 'Router replacement needed', 'My router keeps overheating and shutting down. It''s only 8 months old. Can I get a replacement? Is this covered under warranty?'),
('Telecom', 'International roaming charges', 'I''m traveling to Europe for two weeks and I want to avoid huge roaming charges. What international plans do you offer? Can I add a temporary international package?'),
('Telecom', 'Bundle services discount', 'I currently have internet service with you. If I add TV and phone, do you offer a bundle discount? What would be the total monthly cost?'),
('Telecom', 'Installation appointment reschedule', 'I have a technician scheduled to come tomorrow at 2pm but I need to change it. Can we reschedule for later in the week? My work schedule changed.'),
('Telecom', 'Mobile device trade-in', 'I want to upgrade my phone and trade in my current device. What''s the trade-in value for an iPhone 12 in good condition? How does the process work?'),
('Telecom', 'Unlock mobile phone', 'I''ve finished my contract and I''d like to unlock my phone so I can use it with another carrier when I travel. What''s the process? Is there a fee?'),
('Telecom', 'Cancellation without penalty', 'I''m moving to an area where you don''t provide service. Can I cancel my contract without paying an early termination fee? I still have 6 months left on my contract.'),
('Telecom', 'Email not working', 'I can''t send or receive emails through my account. I keep getting an error message about server connection. Can you help fix this?'),
('Telecom', 'WiFi coverage extension', 'I have dead zones in my house where WiFi doesn''t reach. Do you offer WiFi extenders? How much do they cost and will they work with my current router?'),
('Telecom', 'Promotional offer inquiry', 'I saw an ad for a promotional deal that''s $20 cheaper than what I''m currently paying. Can existing customers get this deal or is it only for new customers?'),
('Telecom', 'Parental controls setup', 'I need to set up parental controls to limit my kids'' internet access during homework time. How do I configure this on my router?'),
('Telecom', 'Landline to VoIP conversion', 'I still have a traditional landline but I''m interested in switching to VoIP to save money. What are the pros and cons? Is there a difference in call quality?'),
('Telecom', 'Data usage tracking', 'I''m getting close to my data limit but I''m not sure what''s using so much data. Can you show me a breakdown of my data usage? Is there an app to monitor this?'),
('Telecom', 'Static IP address request', 'I run a small business from home and I need a static IP address. Do you offer this? What''s the additional monthly cost?'),
('Telecom', 'TV channel package change', 'I want to downgrade my TV package because I don''t watch most of the channels. Can I switch to a basic package mid-contract? What channels would I keep?'),
('Telecom', 'Service address change', 'I''m moving next month within the same city. Can I transfer my service to my new address? Is there a fee? Will there be any downtime?');
